=== perf3ctstyle/FourthTask/src/test/resources/TouristVouchers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/TouristVouchers"
        xmlns:tns="http://www.example.com/TouristVouchers"
        elementFormDefault="qualified">

    <element name="TouristVouchers">
        <complexType>
            <sequence>
                <element ref="tns:ForeignTouristVoucher"
                         minOccurs="2"
                         maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="AbstractTouristVoucher">
        <sequence>
            <element name="transport">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="car" />
                        <enumeration value="plane" />
                        <enumeration value="boat" />
                        <enumeration value="train" />
                    </restriction>
                </simpleType>
            </element>

            <element name="currency">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="USD" />
                        <enumeration value="EUR" />
                        <enumeration value="BYN" />
                    </restriction>
                </simpleType>
            </element>

            <element name="costValue" type="positiveInteger"/>
        </sequence>

        <attribute name="id" use="required">
                <simpleType>
                    <restriction base="ID">
                        <pattern value="v\d{6}" />
                    </restriction>
                </simpleType>
        </attribute>
    </complexType>

    <complexType name="ForeignTouristVoucher">
        <complexContent>
            <extension base="tns:AbstractTouristVoucher">
                <sequence>
                    <element name="country" type="string"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="PilgrimageTouristVoucher">
        <complexContent>
            <extension base="tns:ForeignTouristVoucher">
                <attribute name="security" type="boolean" use="optional" default="false"/>
            </extension>
        </complexContent>
    </complexType>

    <element name="ForeignTouristVoucher" type="tns:ForeignTouristVoucher" />
    <element name="PilgrimageTouristVoucher" type="tns:PilgrimageTouristVoucher" substitutionGroup="tns:ForeignTouristVoucher" />

</schema>

=== perf3ctstyle/FourthTask/src/test/resources/TouristVouchers.xml
<?xml version="1.0" encoding="UTF-8" ?>
<TouristVouchers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xmlns="http://www.example.com/TouristVouchers"
                 xsi:schemaLocation="http://www.example.com/TouristVouchers  TouristVouchers.xsd">

    <ForeignTouristVoucher id="v555666">
        <transport>car</transport>
        <currency>USD</currency>
        <costValue>200</costValue>
        <country>Saudi Arabia</country>
    </ForeignTouristVoucher>

    <ForeignTouristVoucher id="v123321">
        <transport>plane</transport>
        <currency>EUR</currency>
        <costValue>1000</costValue>
        <country>Turkey</country>
    </ForeignTouristVoucher>

    <PilgrimageTouristVoucher id="v932234">
        <transport>train</transport>
        <currency>BYN</currency>
        <costValue>500</costValue>
        <country>Israel</country>
    </PilgrimageTouristVoucher>

    <PilgrimageTouristVoucher id="v551346" security="true">
        <transport>boat</transport>
        <currency>USD</currency>
        <costValue>1350</costValue>
        <country>India</country>
    </PilgrimageTouristVoucher>

</TouristVouchers>
